
import { Navbar } from "@/components/ui/navbar/Navbar";
import { Inter } from "next/font/google";
import "../globals.css";
import { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <div   >
        <Navbar />
        {/* <svg className="absolute bottom-0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320">
          <path
         
            fill="#000b76"
            fill-opacity="1"
            d="M0,32L48,74.7C96,117,192,203,288,218.7C384,235,480,181,576,138.7C672,96,768,64,864,74.7C960,85,1056,139,1152,165.3C1248,192,1344,192,1392,192L1440,192L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z"
          ></path>
        </svg> */}

        {/* <Sidebar/> */}

        {children}
      </div>
   
  );
}
